HW_MVC_Core_11_Roles_2/Controllers/ProductsController.cs
using HW_MVC_Core_11_Roles_2.DbContexts;
using HW_MVC_Core_11_Roles_2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop_app.Models;

namespace Shop_app.Controllers
{

    public class ProductsController : Controller
    {
        private readonly UserContext? _userContext;
        private readonly ProductDbContext _productDbContext;
        public ProductsController(UserContext ?userContext, ProductDbContext productDbContext)
        {
            _userContext = userContext ?? throw new ArgumentNullException("Error, Context is reqired  ...");
            _productDbContext = productDbContext ?? throw new ArgumentNullException("Error Product context is not found");
        }
        //================================================================================
        [HttpGet]
        public IActionResult Index()
        {
            return View(_productDbContext.Products.ToList());
            // Ваш код
            //return View(ProductCollection.Products);
        }
        //================================================================================
        [HttpGet]
        public IActionResult Details(Guid? id)
        {
            
            if (id == null)
            {
                id = new Guid("19BC4394-0A11-488E-AA56-19197159760E");
            }

            var product = _productDbContext.Products.FirstOrDefault(m => m.Id == id);
            if (product == null)
            {
                return BadRequest("Product not found");
            }

            return View(product);
        }
        //================================================================================
        [HttpPost]
        public IActionResult Details(Product? product)
        {
            //id = new Guid("19BC4394-0A11-488E-AA56-19197159760E");
            if (product?.Id == null)
            {
                if (product == null)
                {
                    return NotFound();
                }
                return NotFound();
            }

            //var product = _productDbContext.Products.FirstOrDefault(m => m.Id == id);
            
            return RedirectToAction("Update",product);
        }
        //================================================================================
        [Authorize(Roles = "admin")]
        [HttpGet]
        public ViewResult Create() => View();
        //================================================================================
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Price,Description")] Product product)
        {
            _productDbContext.Products.Add(product);
            _productDbContext.SaveChanges();

            return RedirectToAction("Details", product);
        }
        //================================================================================
        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Update(Guid? id)
        {
            if (id == null)
            {
                id = new Guid("19BC4394-0A11-488E-AA56-19197159760E");
            }
            if (_productDbContext.Products.FirstOrDefault(p => p.Id == id) == null)
            {
                return BadRequest("Id is not exist");
            }
            return View(_productDbContext.Products.FirstOrDefault(p => p.Id == id));
        }
        //================================================================================
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Guid?id,[Bind("Id,Name,Price,Description")] Product? product)
        {
            var existingProduct = await _productDbContext.Products.FirstOrDefaultAsync(p => p.Id == id);

            if (existingProduct == null)
            {
                return BadRequest("Product not found");
            }
            if (product == null)
            {
                return BadRequest("Product data is required.");
            }

            existingProduct.Price = product.Price;
            existingProduct.Description = product.Description;
            existingProduct.Name = product.Name;

            _productDbContext.SaveChanges();
            return RedirectToAction("Details",new {id = existingProduct.Id});
        }
        //================================================================================
        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            // Перевіряємо, чи передано коректний id
            if (id == null)
            {
                id = new Guid("19BC4394-0A11-488E-AA56-19197159760E");
            }

            // Знаходимо продукт у базі даних
            var product = await _productDbContext.Products.FirstOrDefaultAsync(p => p.Id == id);

            // Якщо продукт не знайдено
            if (product == null)
            {
                return NotFound();
            }

            return View(product); // Показуємо сторінку з підтвердженням видалення
        }
        //================================================================================
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            // Знаходимо продукт у базі даних
            var product = await _productDbContext.Products.FindAsync(id);

            // Якщо продукт не знайдено
            if (product == null)
            {
                return NotFound();
            }

            // Видаляємо продукт з бази даних
            _productDbContext.Products.Remove(product);

            // Зберігаємо зміни
            await _productDbContext.SaveChangesAsync();

            // Повертаємось до списку продуктів після видалення
            return RedirectToAction("Index");
        }
    }
}

HW_MVC_Core_11_Roles_2/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Shop_app.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        //Продовжити назначення ролі
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserController(
            UserManager<IdentityUser> userManager, 
            SignInManager<IdentityUser> signInManager, 
            RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(string roleName)
        {
            if (string.IsNullOrEmpty(roleName))
            {
                return BadRequest("Role name is important ...");
            }
            var roleExists = await _roleManager.RoleExistsAsync(roleName);
            if(roleExists)
            {
                return BadRequest("Role already exists ...");
            }
            if(User.Identity.IsAuthenticated)
            {
                var role = new IdentityRole { Name = roleName };
                var result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return Ok($"The role: {role.Name} is created ...");
                }
                return BadRequest(Json(result.Errors));
            }
            return BadRequest("Role create error ...");
        }
        [HttpGet]
        public IActionResult AssignRole()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(string email, string password)
        {
            // Проверяем, что email и пароль были переданы
            if (string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password))
            {
                // Если email или пароль отсутствуют, возвращаем ошибку
                return BadRequest("Email и пароль обязательны.");
            }

            // Создаем нового пользователя IdentityUser с указанным email
            var user = new IdentityUser
            {
                UserName = email,
                Email = email,
                EmailConfirmed = true
            };

            // Используем UserManager для создания пользователя с переданным паролем
            var result = await _userManager.CreateAsync(user, password);

            // Если создание прошло успешно
            if (result.Succeeded)
            {
                // Возвращаем успешный ответ с сообщением
                //return Ok("Пользователь создан.");
                return RedirectToAction("Index", "Home");
            }

            // Если возникли ошибки, добавляем их в ModelState для отображения пользователю
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            // Возвращаем ошибки, если не удалось создать пользователя
            return BadRequest(ModelState);
        }
        [HttpPost]
        public async Task<IActionResult> AssignRole(string id, string roleName)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(roleName))
            {
                return BadRequest("Id or Name Role are important ...");
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound("The user not found ...");
            }
            var roleExists = await _roleManager.RoleExistsAsync(roleName);
            if (!roleExists)
            {
                return NotFound($"The role {roleName} not found ...");
            }
            var result = await _userManager.AddToRoleAsync(user, roleName);
            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            return BadRequest(Json(result.Errors));
        }
        // POST-метод для создания нового пользователя

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {
            // Проверяем, что email и пароль были переданы
            if (string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password))
            {
                // Если email или пароль отсутствуют, возвращаем ошибку
                return BadRequest("Email и пароль обязательны.");
            }
            var result = await _signInManager.PasswordSignInAsync(
                email, 
                password,
                isPersistent: false,
                lockoutOnFailure: false
                );
            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            return BadRequest("Email or password are error ...");
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

HW_MVC_Core_11_Roles_2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shop_app.styles.css" asp-append-version="true" />
    
    <link href="~/css/Style1.css" rel="stylesheet" />
</head>
<body>
    <div class="form-container">

        <header>
            @if (User.Identity.IsAuthenticated)
            {
                <span>Hello, @User.Identity.Name</span>
                //@Html.AntiForgeryToken()
                <form asp-action="Logout" asp-controller="User" method="post">
                    <button type="submit">LogOut</button>
                </form>

                <div class="menu">
                    <a href="/">Home</a>
                    <a asp-controller="User" asp-action="Create">Create New</a>
                    <a asp-controller="User" asp-action="LogIn">LogIn</a>
                    <a asp-controller="User" asp-action="CreateRole">Create Role</a>
                    <a asp-controller="User" asp-action="AssignRole">Manage of Roles</a>
                </div>
            }
            else
            {
                <div class="menu">
                    <a href="/">Home</a>
                    <a asp-controller="User" asp-action="Create">Create New</a>
                    <a asp-controller="User" asp-action="LogIn">LogIn</a>
                </div>
            }
            @if (User.IsInRole("admin"))
            {
                <div class="menu">
                    <h1>Products</h1>
                    <a class="menu" asp-controller="Products" asp-action="Index">Read</a>

                    <a class="menu" asp-controller="Products" asp-action="Create">Create</a>

                    <a class="menu" asp-controller="Products" asp-action="Details">Details</a>
                    <a class="menu" asp-controller="Products" asp-action="Update">Update</a>

                    <a class="menu" asp-controller="Products" asp-action="Delete">Delete</a>
                </div>
            }
            else
            {<div class="menu">
    <h1>Products</h1>
    <a class="menu" asp-controller="Products" asp-action="Index">Read</a>

    <a class="menu" asp-controller="Products" asp-action="Details">Details</a>
    
</div>  
            }


        </header>
        <div class="container">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <div>
                &copy; 2024 - Identity
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>